id: P009287
initial_creation_type: ocr
created_at: 25/03/2020
last_modified_at: 2021-12-19 19:31:40.739089
source_metadata:
  id: bdr:W1KG1253
  title: མི་དབང་རྟོགས་བརྗོད
  author: ''
  volumes:
    8287c735ddc944ab86fa5d77009fd026:
      image_group_id: I1KG1276
      title: ''
      volume_number: 1
      total_pages: 792
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
